### ISSUE TITLE
插件的使用

### ISSUE THREAD

**Issue by bx2651** [Spikef/vue-theme-switch-webpack-plugin#1]
您好，请问下，我按照example，先import了样式文件，然后Vue.use(window.VueThemeSwitcher),然后在app.vue文件里添加了切换按钮，还是不能切换主题，请问我应该怎么操作？
非常感谢

**Comment by Spikef** [comment]
https://github.com/Spikef/vue-theme-switch-webpack-plugin/blob/master/example/build/webpack.dev.js#L134
